services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx/https.conf.template:/etc/nginx/templates/default.conf.template:ro
      - certbot_www:/var/www/certbot:ro
      - letsencrypt:/etc/letsencrypt:ro
